version: "3.8"

services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    pull_policy: never
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/retanaka/data/wp:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    environment:
      - DOMAIN_NAME=retanaka.42.fr

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    pull_policy: never
    container_name: wordpress
    env_file: .env
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/retanaka/data/wp:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    pull_policy: never
    container_name: mariadb
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/retanaka/data/db:/var/lib/mysql
    networks:
      - inception
    restart: always

networks:
  inception:

