version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports: "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    secrets:
      - tls_cert
      - tls_key

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    secrets:
      - db_password
      - db_root_password

volumes:
  wp_data:
  db_data:

networks:
  inception:

secrets:
  tls_cert:
    file: ../secrets/tls_cert.txt
  tls_key:
    file: ../secrets/tls_key.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

